### ISSUE TITLE
Issue with bitnami redis chart (pod not starting)

### ISSUE THREAD

**Issue by rhaamo** [WeblateOrg/helm#110]
**Describe the issue**

`redis-master-0` pod don't start.

```
[38;5;6mredis [38;5;5m14:08:02.92 [0m[38;5;2mINFO [0m ==> ** Starting Redis **
1:C 31 Aug 2021 14:08:02.935 # Can't chdir to '/data': Permission denied
```

**I already tried**

Already tried to drop the whole namespace and reinstall.

**To Reproduce the issue**

I am using a manually created PVC for weblate itself:
```
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: "weblate-pvc"
            namespace: "weblate"
          spec:
            accessModes:
              - ReadWriteMany
            storageClassName: longhorn-2r
            resources:
              requests:
                storage: 1Gi
```

And my helm install call/definition (through ansible):
```
        release_name: weblate
        chart_ref: weblate/weblate
        release_values:
          fullnameOverride: "weblate"
          emailHost: "10.0.0.111"
          serverEmail: weblate@x
          defaultFromEmail: weblate@x
          allowedHosts: weblate.x,localhost
          siteDomain: weblate.x
          adminEmail: x@x
          adminPassword: 123456
          debug: "0"
          postgresql:
            enabled: false
            postgresqlHost: "10.0.0.12"
            postgresqlPassword: 123456
          ingress:
            enabled: false
          persistence:
            existingClaim: "weblate-pvc"
          extraConfig:
            WEBLATE_GITHUB_USERNAME: 123456
            WEBLATE_SOCIAL_AUTH_GITHUB_KEY: 123456
            WEBLATE_SOCIAL_AUTH_GITHUB_SECRET: 123456
            WEBLATE_REGISTRATION_OPEN: "1"
            WEBLATE_TIME_ZONE: 'Europe/Paris'
            WEBLATE_ENABLE_HTTPS: "1"
```

I can see a PVC for redis which is green `redis-data-weblate-redis-master-0 `, but the pod don't start because of some right issues.
