### ISSUE TITLE
0.4.2 breaks support for external Postgres & Redis usage

### ISSUE THREAD

**Issue by Croissong** [WeblateOrg/helm#121]
### Describe the issue

b1aa48d5c5ec3f49648af7bc714e72825399c48b disables postgres & redis env vars if the subcharts are disabled.
In our setup, we do not want to deploy Redis & Postgres via the subcharts, but relied on the env vars to configure the connection to our external Postgres & Redis resources.

Since the Postgres & Redis charts don't [export their values](https://helm.sh/docs/topics/charts/#importing-child-values-via-dependencies), I think there isn't any better way other than duplicating the connection settings both for the parent- and subcharts.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Our values.yml file:
```
[...]
postgresql:
  postgresqlHost: azure.com
  postgresqlUsername: postgres@azure.com
  postgresqlPassword: <pw>
  postgresqlDatabase: <db>
  enabled: false

redis:
  # same as postgres 
```
### Expected behavior

`POSTGRES_*` env vars are still injected into weblate container
