### ISSUE TITLE
Helm Version 0.4.2 doesn't print Postgres or Redis env vars into deployment.

### ISSUE THREAD

**Issue by Spittal** [WeblateOrg/helm#128]
### Describe the issue

Recently updated to version 0.4.2 and deployed. I noticed that the app wasn't working to I inspected the rendered yaml and noticed none of the postgres or redis env vars were in there. Despite the relevant section of my values file looking like this:

```yaml
postgresql:
  enabled: false
  postgresqlHost: // removed for issue
  postgresqlUsername: "postgres"
  postgresqlDatabase: "weblate"

redis:
  enabled: false
  password: "" // My redis instance has no password
  redisHost: // removed for issue
```

The issue is clearly this commit: https://github.com/WeblateOrg/helm/commit/b1aa48d5c5ec3f49648af7bc714e72825399c48b

But the [docs](https://github.com/WeblateOrg/helm/tree/main/charts/weblate) contradict this commit by saying
> External postgres database endpoint, to be used if postgresql.enabled == false

and

> External redis database endpoint, to be used if redis.enabled == false

Seems like there was a miscommunication as to what `enabled` means. Perhaps renaming that configuration key from `enabled` to `external` to make things more clear?

## Workaround
just append `--version 0.4.1` to your helm command.
