### ISSUE TITLE
allow to disable security context

### ISSUE THREAD

**Issue by thpham** [WeblateOrg/helm#184]
### Describe the issue

Installing Weblate via Helm charts on Openshift is currently non trivial. Openshift manages UID and GID of each container per default and ensures it's not running as root.

In some context we include weblate as subchart to be able to deploy other stuff in the same time like `externalSecretName`.

The current default values.yaml explicitly define:

```
podSecurityContext:
  fsGroup: 1000

securityContext: {}
```

which is **NOT** possible to override due to current [helm bug](https://github.com/helm/helm/issues/9136).

I saw many project starting to add a boolean flag to enable or not.
A bit like what you can do with your bitnami redis and postgresql subcharts.

```yaml
postgresql:
  securityContext:
    enabled: false
  containerSecurityContext:
    enabled: false

redis:
  securityContext:
    enabled: false
  containerSecurityContext:
    enabled: false
```

Would you be ready to consider such a change for the chart ?

thank you for your considerations.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

-

### Expected behavior

-
