### ISSUE TITLE
Release notes for helm chart

### ISSUE THREAD

**Issue by zisuu** [WeblateOrg/helm#338]
### Describe the problem

Currently I can not find any kind of release notes for new releases of the weblate helm chart. The only way to see what happened and what must be changed in the yaml deployment or values files is to go trough the commit history manually and read line-by-line trough the code changes. This is very inefficient and still not save to catch all changes.

### Describe the solution you'd like

I'd like to have a release note for each new weblate helm chart release which mentions what has been changed any also if and what needs to be changed to migrate from the pervious version to the new one. Something like this would be amazing: https://github.com/WeblateOrg/weblate/releases

### Describe alternatives you've considered

read trough the git commit history manually, line-by-line (current approach)

**Comment by nijel** [comment]
Yes, that would be great. This repo really needs more love because there is currently nobody pushing it forward.

**Comment by f3k-tech** [comment]
Artifacthub has actually got a built-in functionality for this. You simply add annotations in Chart.yaml.
Based on this artifacthub creates a webview and a changelog.md that you could link to or download elsewhere:
Markdown example: https://artifacthub.io/api/v1/packages/helm/f3k-tech/libretranslate/changelog.md
Webview example: https://artifacthub.io/packages/helm/f3k-tech/libretranslate?modal=changelog

This is how you include it in Chart.yml

### Simple
```yml
annotations:
  artifacthub.io/changes: |
    - Support for ci/cd pipelines
    - Versions index to changelog modal
    - Allow publishers to include screenshots in packages    
```

### Advanced
```yml
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Added new login feature for enhanced user authentication.
    - kind: changed
      description: Updated data processing to increase efficiency.
    - kind: deprecated
      description: Deprecated old API endpoints in favor of newer ones.
    - kind: removed
      description: Removed legacy support for outdated database systems.
    - kind: fixed
      description: Fixed issue causing intermittent crashes in high-load scenarios.
    - kind: security
      description: Patched vulnerability in the authentication module.
```
