### ISSUE TITLE
FATAL:  password authentication failed for user "weblate"

### ISSUE THREAD

**Issue by cianiandreadev** [WeblateOrg/helm#526]
### Describe the issue

Hi All,

I tried to search also for similar issues here but the only I found had no answer.

I am trying to install using helm but I always get the following error:

```
psql: error: connection to server at "weblate-postgresql" (10.43.238.95), port 5432 failed: FATAL:  password authentication failed for user "weblate"
```

Moreover, it seems that the `postgres-password` is required together with the `postgresql-password` in the secret, otherwise the deployment does not start.

Could it be I am missing something? 

Following my `values.yml`

```yml
nameOverride: 'weblate'
fullnameOverride: 'weblate'
adminEmail: 'mymail'
adminUser: 'admin'
adminPassword: 'mypasswd'

# siteTile -- Site title
siteTitle: Andrea's Weblate
# siteDomain -- Site domain
siteDomain: weblate.intranet

existingSecret: 'secret-weblate'

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use. If not set and create is true, a name is generated using the fullname template
  name: service

ingress:
  enabled: true
  ingressClassName: 'traefik'
  hosts:
    - host: weblate.intranet
      paths:
        - path: /
          pathType: Prefix

persistence:
  enabled: true
  userName: "weblate"
  existingClaim: 'pvc-weblate'
  postgresPassword: "weblate"
  storageClass: "longhorn"
  size: 5Gi

postgresql:
  auth:
    existingSecret: 'secret-weblate'

redis:
  auth:
    existingSecret: 'secret-weblate' 

### I already tried

- [x] I've read and searched [the documentation](https://docs.weblate.org/).
- [x] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

`helm install weblate weblate/weblate -n intranet -f andrea-values.yml` with values provided.

### Expected behavior

_No response_

### Screenshots

_No response_

### Exception traceback

```pytb

```

**Comment by Mart-Kuc** [comment]
Hi @cianiandreadev,

If you specify the `postgresql.auth.existingSecret` key, the Deployment retrieves the database password from the specified secret. This means your database password will be stored in `secret-weblate`.

Make sure that the key inside your secret matches the value you set in `.Values.postgresql.auth.secretKeys.userPasswordKey`.

You have two options:

1. Remove the existing secret from the values file and define the correct username and password directly in the values file.
2. Use your own secret and ensure the correct key is specified.

**Comment by cianiandreadev** [comment]
Hi @Mart-Kuc ,

Thanks for the quick answer!

So, let me see if I understood correctly, I'm still pretty confused

In my `secret-weblate` file I have the following (sample passwords of course):

```
[...]
postgresql-password : weblate
postgresql-user : weblate
redis-password: weblate
[...]
```

and I updated the `values.yml` as following: 

```yml
[...]
postgresql:
  auth:
    secretKeys:
      userPasswordKey: 'postgresql-password'

redis:
  auth:
    existingSecret: 'secret-weblate'
[...]
```

Since it says `userPasswordKEY` I passed the KEY that, inside the `secret-weblate` matches the password used, so `postgresql-password`.
