### ISSUE TITLE
Add custom timeoutSeconds for Readiness/Liveness probes

### ISSUE THREAD

**Issue by siarheitrus** [WeblateOrg/helm#583]
### Describe the problem

Currently i can't change timeout for Readiness/Liveness probes (default 1 sec).

_helm/charts/weblate/templates/deployment.yaml_
```
         {{- if .Values.livenessProbe }}
          livenessProbe:
            httpGet:
              path: {{ $.Values.sitePrefix }}/healthz/
              port: http
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            httpGet:
              path: {{ $.Values.sitePrefix }}/healthz/
              port: http
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          {{- end }}
```

But under load my timeout can exceed 2 sec.

### Solution brainstorm

I propose adding timeoutSeconds to the readiness and liveness probes.

_helm/charts/weblate/templates/deployment.yaml_
```
         {{- if .Values.livenessProbe }}
          livenessProbe:
            httpGet:
              path: {{ $.Values.sitePrefix }}/healthz/
              port: http
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            httpGet:
              path: {{ $.Values.sitePrefix }}/healthz/
              port: http
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          {{- end }}
```
